### ISSUE TITLE
add FizzBuzz

### ISSUE THREAD

**Issue by alexanderywang** [johnptmcdonald/tinyhelp#11]
Write a program that prints the numbers from 1 to 100. But for multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz".

**Comment by johnptmcdonald** [comment]
What would be the developer use for this? i.e. Is there ever a time when building an app and you need this?

**Comment by alexanderywang** [comment]
good point.
