### ISSUE TITLE
add shuffle function

### ISSUE THREAD

**Issue by damatomike** [johnptmcdonald/tinyhelp#19]
developer can pass in an array and generate a shuffled version of that array, say for example like a deck of cards. This array can contain numbers and strings.

[1,2,3,4,5, 'FSA'] can be shuffled to random iterations such as:

[2,1,3,'FSA, 4,5]
[5,3,'FSA',1,2,4]
etc.

**Comment by johnptmcdonald** [comment]
Yes please! Use Let's make two shuffles - one regular and one in-place. Use fisher-yates for in-place.
